import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Tech & Gadgets', slug: 'tech' },
  { id: '2', name: 'Home & Kitchen', slug: 'home' },
  { id: '3', name: 'Fitness & Outdoors', slug: 'fitness' },
  { id: '4', name: 'Fashion', slug: 'fashion' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'UltraNoise Cancelling Headphones',
    description: 'Experience pure silence with our top-rated noise cancelling technology. 30-hour battery life.',
    price: 299.99,
    originalPrice: 349.99,
    rating: 4.8,
    reviews: 1240,
    category: 'tech',
    imageUrl: 'https://picsum.photos/400/300?random=1',
    affiliateLink: '#',
    isBestSeller: true,
  },
  {
    id: 'p2',
    title: 'Smart Home Hub Max',
    description: 'Control your entire home with voice commands. Compatible with over 10,000 devices.',
    price: 129.00,
    rating: 4.5,
    reviews: 850,
    category: 'tech',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    affiliateLink: '#',
  },
  {
    id: 'p3',
    title: 'Ergonomic Mesh Office Chair',
    description: 'Work in comfort all day long. Adjustable lumbar support and breathable mesh back.',
    price: 189.99,
    originalPrice: 250.00,
    rating: 4.7,
    reviews: 3200,
    category: 'home',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    affiliateLink: '#',
    isBestSeller: true,
  },
  {
    id: 'p4',
    title: 'Pro-Series Blender 5000',
    description: 'Crush ice, make smoothies, and prepare hot soups in minutes with this high-speed blender.',
    price: 89.95,
    rating: 4.6,
    reviews: 500,
    category: 'home',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    affiliateLink: '#',
  },
  {
    id: 'p5',
    title: 'TrailBlazer Hiking Boots',
    description: 'Waterproof, durable, and lightweight. Perfect for any terrain.',
    price: 145.00,
    rating: 4.9,
    reviews: 210,
    category: 'fitness',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    affiliateLink: '#',
  },
  {
    id: 'p6',
    title: 'Smart Fitness Watch',
    description: 'Track your heart rate, sleep, and steps. Built-in GPS for runners.',
    price: 199.50,
    originalPrice: 229.50,
    rating: 4.4,
    reviews: 890,
    category: 'fitness',
    imageUrl: 'https://picsum.photos/400/300?random=6',
    affiliateLink: '#',
  },
  {
    id: 'p7',
    title: 'Minimalist Leather Wallet',
    description: 'Slim, genuine leather wallet with RFID protection.',
    price: 45.00,
    rating: 4.8,
    reviews: 1500,
    category: 'fashion',
    imageUrl: 'https://picsum.photos/400/300?random=7',
    affiliateLink: '#',
  },
  {
    id: 'p8',
    title: 'Vintage Denim Jacket',
    description: 'Classic style that never fades. 100% cotton denim.',
    price: 79.99,
    rating: 4.3,
    reviews: 400,
    category: 'fashion',
    imageUrl: 'https://picsum.photos/400/300?random=8',
    affiliateLink: '#',
  },
];
